const text = {
    "tr" : {
        // EachAsset.js
        editModalTitle: "Varlığı Düzenle",
        editModalContent1: "Bu varlığınızı düzenliyorsunuz: ",
        editModalContent2: "Şu değerden: ",
        editModalContent3: "Şu Değere",
        deleteModalTitle: "Varlığı Silme",
        deleteModalContent: "Bu varlığı siliyorsunuz: ",
        saveButtonToolTip: "Kaydet",
        cancelButtonToolTip: "İptal",
        editButtonToolTip: "Düzenle",
        deleteButtonToolTip: "Sil",
        messageUpdateAsset: "Varlık başarıyla güncellendi.",
        messageInvalidInput: "Lütfen geçerli bir değer giriniz.",
        messageDeleteAsset: "Varlık başarıyla silindi.",
        okText: "Onayla",
        cancelText: "İptal",
        // Loading.js
        loadingBottomText: "Yatırımcılar için Profesyonel Cüzdan",
        // Navbar.js
        wallet: "Cüzdanınız",
        profile: "Profil",
        logout: "Çıkış Yap",
        login: "Giriş Yap",
        register: "Üye Ol",
        // Login.js and Register.js
        inValidEmail: "Lütfen geçerli bir email adresi giriniz.",
        inValidPassword: "Lütfen geçerli bir şifre giriniz.",
        invalidName: "Lütfen isim ve soyisiminizi giriniz.",
        successfullyLogin: "Başarılı bir şekilde giriş yaptınız.",
        successfullyRegister: "Başarılı bir şekilde üye oldunuz.",
        email: "Email",
        password: "Şifre",
        name: "İsim ve Soyisim",
        loginButton: "Giriş Yap",
        goToRegister: "Henüz bir hesabınız yok mu? Hızlıca kayıt olun.",
        registerButton: "Üye Ol",
        goToLogin: "Zaten bir hesabınız var mı? Hızlıca giriş yapın.",
        selectPhysical: "Lütfen sahip olduğunuz fiziksel yatırım varlıklarınızı seçiniz.",
        selectCrypto: "Lütfen sahip olduğunuz kripto paralarınızı seçiniz.",
        selectFund: "Lütfen sahip olduğunuz yatırım fonlarını seçiniz.",
        physicalTitle: "Fiziksel Yatırımlar",
        crpytoTitle: "Kripto Paralar",
        fundTitle: "Yatırım Fonları",
        // Profile.js
        addAssetSuccessMessage: "Varlıklar başarı ile eklendi.",
        profileAssets: "Varlıklar",
        infoTooltipTitle: "Ondalıklı kısımlar için '.' kullanın. Binden büyük sayılar için bir işaret kullanmayın. Örn. Varlık: 42363.53",
        noAsset: "Hiçbir varlığınız yok.",
        addAsset: "Varlık Ekle",
        addButtonTitle: "Ekle",
        // Wallet.js
        emptyWallet1: "Cüzdanınızda hiç bir varlık yok gibi görünüyor.",
        emptyWallet2: "Eğer",
        emptyWallet3: "Profil Sayfanıza",
        emptyWallet4: "giderseniz, varlık ekleyebilirsiniz.",
        tab1: "Dairesel",
        tab2: "Sütun",
        tab3: "Doğrusal",
        total: "Toplam",
        code: 'Kod',
        price: 'Fiyat',
        daily: 'Günlük',
        asset: 'Varlık',
        
    },
    "en": {
        // EachAsset.js
        editModalTitle: "Edit Asset",
        editModalContent1: "You are editing: ",
        editModalContent2: "From: ",
        editModalContent3: "To",
        deleteModalTitle: "Delete Asset",
        deleteModalContent: "You are deleting: ",
        saveButtonToolTip: "Save",
        cancelButtonToolTip: "Cancel",
        editButtonToolTip: "Edit",
        deleteButtonToolTip: "Delete",
        messageUpdateAsset: "Asset updated successfully.",
        messageInvalidInput: "Please enter valid quantity.",
        messageDeleteAsset: "Asset deleted successfully.",
        okText: "Ok",
        cancelText: "Cancel",
        // Loading.js
        loadingBottomText: "Professional Wallet for Investors",
        // Navbar.js
        wallet: "Your Wallet",
        profile: "Profile",
        logout: "Logout",
        login: "Login",
        register: "Register",
        // Login.js and Register.js
        inValidEmail: "Please Enter Valid Email Address",
        inValidPassword: "Please Enter Valid Password",
        invalidName: "Please Enter Your Name and Surname",
        successfullyLogin: "Successfully Logged In.",
        successfullyRegister: "Successfully Registered.",
        email: "Email",
        password: "Password",
        name: "Name and Surname",
        loginButton: "Login",
        goToRegister: "You don't have an account? Register quickly.",
        registerButton: "Register",
        goToLogin: "Already have an account? Login quickly.",
        selectPhysical: "Please select physical investments you have.",
        selectCrypto: "Please select investments funds you have.",
        selectFund: "Please select crypto moneys you have.",
        physicalTitle: "Physical Investments",
        crpytoTitle: "Crypto Moneys",
        fundTitle: "Investments Funds",
        // Profile.js
        addAssetSuccessMessage: "Assets are added successfully.",
        profileAssets: "Assets",
        infoTooltipTitle: "Use '.' for decimal, Don't use anything for thousands. e.g. Asset: 42363.53",
        noAsset: "You Have No Asset.",
        addAsset: "Add Assets",
        addButtonTitle: "Add",
        // Wallet.js
        emptyWallet1: "Looks like you didn't add any asset to your wallet.",
        emptyWallet2: "Go to",
        emptyWallet3: "Your Profile Page",
        emptyWallet4: "and start to add your assets.",
        tab1: "Pie Chart",
        tab2: "Bar Chart",
        tab3: "Line Chart",
        total: "Total",
        code: 'Code',
        price: 'Price',
        daily: 'Daily',
        asset: 'Asset',
    },
}

export default text;